// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.bk.spring.proto.bkprotobuf.models;

public final class TrainingCourse {
  private TrainingCourse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bk_spring_proto_bkprotobuf_Course_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bk_spring_proto_bkprotobuf_Course_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bk_spring_proto_bkprotobuf_Student_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bk_spring_proto_bkprotobuf_Student_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bk_spring_proto_bkprotobuf_Student_PhoneNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bk_spring_proto_bkprotobuf_Student_PhoneNumber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014schema.proto\022\036com.bk.spring.proto.bkpr" +
      "otobuf\"c\n\006Course\022\n\n\002id\030\001 \001(\005\022\023\n\013course_n" +
      "ame\030\002 \001(\t\0228\n\007student\030\003 \003(\0132\'.com.bk.spri" +
      "ng.proto.bkprotobuf.Student\"\226\002\n\007Student\022" +
      "\n\n\002id\030\001 \001(\005\022\022\n\nfirst_name\030\002 \001(\t\022\021\n\tlast_" +
      "name\030\003 \001(\t\022\r\n\005email\030\004 \001(\t\022B\n\005phone\030\005 \003(\013" +
      "23.com.bk.spring.proto.bkprotobuf.Studen" +
      "t.PhoneNumber\032^\n\013PhoneNumber\022\016\n\006number\030\001" +
      " \001(\t\022?\n\004type\030\002 \001(\01621.com.bk.spring.proto" +
      ".bkprotobuf.Student.PhoneType\"%\n\tPhoneTy",
      "pe\022\n\n\006MOBILE\020\000\022\014\n\010LANDLINE\020\001B<\n(com.bk.s" +
      "pring.proto.bkprotobuf.modelsnewB\016Traini" +
      "ngCourseP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_bk_spring_proto_bkprotobuf_Course_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bk_spring_proto_bkprotobuf_Course_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bk_spring_proto_bkprotobuf_Course_descriptor,
        new java.lang.String[] { "Id", "CourseName", "Student", });
    internal_static_com_bk_spring_proto_bkprotobuf_Student_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_bk_spring_proto_bkprotobuf_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bk_spring_proto_bkprotobuf_Student_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "Email", "Phone", });
    internal_static_com_bk_spring_proto_bkprotobuf_Student_PhoneNumber_descriptor =
      internal_static_com_bk_spring_proto_bkprotobuf_Student_descriptor.getNestedTypes().get(0);
    internal_static_com_bk_spring_proto_bkprotobuf_Student_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bk_spring_proto_bkprotobuf_Student_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
